// Этот массив создан, чтобы поиск миссий работал
const allSetsArray = [
    "чтотакоеto",
    "PRESENTSIMPLE",

    "technologic3b1",
    "technologic2a2",
    "technologic1a1",

    "santalapfart3c1",
    "santalapfart2b2",
    "santalapfart1b1",

    "questions111clothesb1",
    "clothes03",
    "clothes02",
    "clothes01",

    "questions003",

    "m009",
    "m008",
    "m007",
    "verbs002",
    "verbs001",
    "sara",

    "compareadjectiveser",
    "compareadjectivesmore",
    "compareadjectivesb2",
    "compareadjectivesb1",
    "adjectivesb1",
    "adjectives09",
    "adjectives08",
    "adjectives07",
    "adjectives06",
    "adjectives05",
    "adjectives04",
    "adjectives03",
    "adjectives02",
    "adjectives01",
    "questions001",
    "m006questions0",
    "m005q1",
    "m004numbers",
    "m003",
    "m002",
    "m001",
    "lettersa1",
    "lettersc2",
    "numbersa1",
    "numbersa2",
    "numbersb1",
    "numbersb2",
    "numbersspeak",
   
    "commonVerbs",
    "technologic",
 
    "abc",
    "xyz",

   
    "mission2",
    "stickyVerbs1",
    "adjectivesbodya1",
    "upperBody",
    "lowerBody",
    "affirmations1",
    "naughtyVerbs",
    "affirmations2",
    
    "time",
    "bm",
    "ac",
    "ae",
    "cf",
    "cg",
    "eg",
    "hm",
    "eh",
    "hr",
    "pr",
    "s1",
    "lr",
    "ls",
    "rs",
    "rt",
    "st",
    "sw",
    "tstar",
    "astar",
    "cook3",
    "spanish",
    "loco",
    "adjquest",
    "anika",
    "understand",
    "allnaughtyverbs",
    "part1bc",
    "part2cd",
    "part3fg",
    "part4bg",
    "part5hl",
    "part6lp",
    "part7hr",
    "part8ss",
    "part9tw",
    "part10awb2",
    "part11awc1",
    "mission1a2time",
    "mission2a2time",
    "blockedSet",
   
 

]
export default allSetsArray