// Этот массив создан, чтобы поиск миссий работал
const allSetsArray = [
    "commonVerbs",
    "technologic",
    "testing",
    "abc",
    "xyz",
    "testOneSeven",
    "when",
    "numbers0",
    "letters",
    "questions0",
    "mission0",
    "formulas0",
    "mission2",
    "mission1",
    "thirtieth",
    "stickyVerbs1",
    "bodyAdj",
    "upperBody",
    "lowerBody",
    "affirmations1",
    "naughtyVerbs",
    "affirmations2",
    "q1",
    "time",
    "bm",
    "ac",
    "ae",
    "cf",
    "cg",
    "eg",
    "hm",
    "eh",
    "hr",
    "pr",
    "s1",
    "lr",
    "ls",
    "rs",
    "rt",
    "st",
    "sw",
    "tstar",
    "astar",
    "cook3",
    "musicCheck",
    "musicCheck",
    "new_mission",
    "spanish",
    "compare",
    "adjquest",
    "anika"


]
export default allSetsArray