// Этот массив создан, чтобы поиск миссий работал
const allSetsArray = [

    "m001",
    "m002",
    "m003",
    "m004",
    "m005",
    "m006",
    "lettersa1",
    "lettersc2",
    "m007",
    "numbersIntro12",
    "numbersa1",
    "numbersa2",
    "numbersb1",
    "numbersb2",
    "numbersspeak",
    "blockedSet",

    "m008q1",
    "m009questions0",
    "questions001",
    "adjectives01",
    "adjectives02",
    "blockedSet",
    "verbs001",
    "verbs002",
    "m010",
    "m011",
    "m012",
    "sara",
    "questions003",


    "adjectives03",
    "adjectives04",
    "adjectives05",
    "paperPlanes",
    "blockedSet",

    "compareadjectivesmore",
    "compareadjectiveser",
    "compareadjectivesb1",
    "adjectives06",
    "adjectives07",
    "adjectives08",
    "adjectives09",
    "adjectivesb1",
    "compareadjectivesb2",

    "clothes01",
    "clothes02",
    "clothes03",
    "questions111clothesb1",

    "mission1a2time",
    "naughtyVerbs",
    "trickyTest1",
    "mission2a2time",
    "anika",
    "gerund",

    "adjectivesbodya1",
    "upperBody",
    "lowerBody",
    "mission2",
    "stickyVerbs1",
    "adjquest",
    "affirmations1",
    "affirmations2",
    "understand",
    "cook3",
    "new_mission",
    "spanish",
    "loco",

    "mission3",
    "travel",
    "bodypartsa1",

    "santalapfart1b1",
    "santalapfart2b2",
    "santalapfart3c1",
    "technologic1a1",
    "technologic2a2",
    "technologic3b1",

]
export default allSetsArray